version: "3.8"  # optional since v1.27.0
services:
  backend:
    image: "mosesisrael/springboot-react-fullstack:latest"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev